import os
os.environ["PYSDL2_DLL_PATH"] = r"D:\Program Files\bin"

import sys
from sdl2 import *
import sdl2.ext
import ctypes
import math


eventNames = ['SDL_FIRSTEVENT'
,'SDL_QUIT'
,'SDL_APP_TERMINATING'
,'SDL_APP_LOWMEMORY'
,'SDL_APP_WILLENTERBACKGROUND'
,'SDL_APP_DIDENTERBACKGROUND'
,'SDL_APP_WILLENTERFOREGROUND'
,'SDL_APP_DIDENTERFOREGROUND'
,'SDL_WINDOWEVENT'
,'SDL_SYSWMEVENT'
,'SDL_KEYDOWN'
,'SDL_KEYUP'
,'SDL_TEXTEDITING'
,'SDL_TEXTINPUT'
,'SDL_KEYMAPCHANGED'
,'SDL_MOUSEMOTION'
,'SDL_MOUSEBUTTONDOWN'
,'SDL_MOUSEBUTTONUP'
,'SDL_MOUSEWHEEL'
,'SDL_JOYAXISMOTION'
,'SDL_JOYBALLMOTION'
,'SDL_JOYHATMOTION'
,'SDL_JOYBUTTONDOWN'
,'SDL_JOYBUTTONUP'
,'SDL_JOYDEVICEADDED'
,'SDL_JOYDEVICEREMOVED'
,'SDL_CONTROLLERAXISMOTION'
,'SDL_CONTROLLERBUTTONDOWN'
,'SDL_CONTROLLERBUTTONUP'
,'SDL_CONTROLLERDEVICEADDED'
,'SDL_CONTROLLERDEVICEREMOVED'
,'SDL_CONTROLLERDEVICEREMAPPED'
,'SDL_FINGERDOWN'
,'SDL_FINGERUP'
,'SDL_FINGERMOTION'
,'SDL_DOLLARGESTURE'
,'SDL_DOLLARRECORD'
,'SDL_MULTIGESTURE'
,'SDL_CLIPBOARDUPDATE'
,'SDL_DROPFILE'
,'SDL_AUDIODEVICEADDED'
,'SDL_AUDIODEVICEREMOVED'
,'SDL_RENDER_TARGETS_RESET'
,'SDL_RENDER_DEVICE_RESET'
,'SDL_USEREVENT'
,'SDL_LASTEVENT'
]

#Map event codes to name strings
eventName = { globals()[name] : name for name in eventNames }



def init(name, width, height):
	"""Inits sdl, create a window and a renderer

	returns window, renderer"""


	SDL_Init(SDL_INIT_VIDEO)
	window = SDL_CreateWindow(name,
		SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
		width, height,
		0)

	renderer = SDL_CreateRenderer(window, -1, 0)

	return window, renderer

def sdlGetTime():
	"Returns a float timestamp in seconds (only useful relative to other stamps)"
	return SDL_GetPerformanceCounter() / SDL_GetPerformanceFrequency()
